// import classnames from 'classnames';
import { html, property, customElement, LitElement } from 'lit-element';
import { pfPrefix } from '../../globals/settings';
import styles from './page-test.scss';

/**
 * Page Header.
 */
@customElement(`${pfPrefix}-page-test-header`)
class PFPageHeaderTest extends LitElement {
  /**
   * Additional button classes
   */
  @property({ reflect: false })
  class = '';

  createRenderRoot() {
    return this.attachShadow({ mode: 'open', delegatesFocus: true });
  }

  render() {
    // const { class: additionalClass } = this;
    // const classes = classnames(additionalClass, `${pfPrefix}-c-page__header`);
    // return html`
    //   <header role="banner" class="${classes}"><slot></slot></header>
    // `;
    return html`
      <slot></slot>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}
export default PFPageHeaderTest;
